# Generated by Django 2.1.1 on 2020-05-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ShipTime'),
        ),
    ]
