# Generated by Django 2.1.1 on 2020-05-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200521_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avail',
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
